### ISSUE TITLE
Cade?

### ISSUE THREAD

**Issue by SmartVulpe** [leonardo-buta/trilha-net-exemplo-explorando-a-linguagem#1]
Só tem o readme.
![Captura de tela 2022-10-22 184634](https://user-images.githubusercontent.com/7051424/197363522-a75c1e75-7a2d-40d8-8cee-b7f91629264e.png)

Aproveitando para descobrir como funciona isso de reportar um problema.

**Comment by leonardo-buta** [comment]
Obrigado Daniel!
Havia me esquecido de subir os arquivos do projeto.
Acabei de subir esse, e nos próximos dias irei subir o restante dos códigos das outras aulas.

Abraço!
